Repository d-kuro/kubectl-fuzzy, pull requests merged in 2020-07, with the labels that each got.

#30 Simplify display the object
  README.md
  docs/assets/kubectl-fuzzy.gif
  docs/assets/preview.jpg
  go.mod
  go.sum
  pkg/cmd/describe.go
  pkg/cmd/exec.go
  pkg/cmd/logs.go
  pkg/cmd/version.go
  pkg/fuzzyfinder/fuzzyfinder.go
  pkg/kubernetes/simplify/simplify.go
Labels: enhancement

#31 Support krew
  README.md
Labels: documentation

#33 Support multi resource type
  .github/workflows/go.yaml
  .golangci.yaml
  pkg/cmd/describe.go
  pkg/cmd/version.go
  pkg/fuzzyfinder/fuzzyfinder.go
Labels: enhancement

#34 Add support commands documentation
  README.md
  docs/commands.md
  go.sum
Labels: documentation

#32 Add create job command to create job from cronjob
  pkg/cmd/create.go
  pkg/cmd/create_job.go
  pkg/cmd/root.go
Labels: enhancement

#35 Add command docs for create
  .github/workflows/go.yaml
  README.md
  docs/commands.md
  pkg/cmd/version.go
Labels: documentation

#43 Support label selector for exec command
  .golangci.yaml
  docs/commands.md
  pkg/cmd/exec.go
  pkg/cmd/version.go
  pkg/fuzzyfinder/fuzzyfinder.go
  pkg/kubernetes/simplify/simplify.go
Labels: enhancement

#48 Add no resource found error handling
  .github/workflows/go.yaml
  .golangci.yaml
  pkg/cmd/create_job.go
  pkg/cmd/describe.go
  pkg/cmd/exec.go
  pkg/cmd/logs.go
  pkg/cmd/version.go
Labels: bug
